version: '3'
services:
  grafana:
    image: grafana/grafana
    container_name: Kuznetsov-DS-netology-grafana
    ports:
      - 80:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./custom.ini:/etc/grafana/custom.ini
    networks:
      - Kuznetsov-DS-netology-grafana  
networks: 
  Kuznetsov-DS-netology-grafana:  
    ipam:
      config:
        - subnet: 10.5.0.0/16
 